# Generated by Django 4.2.7 on 2024-01-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
